name: GitHub Classroom Autograding

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  grade:
    name: Autograding and Reporting
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run grading script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node autograde.js
